version: "3.8"
services:
  server:
    image: "jetbrains/teamcity-server:latest"
    ports:
      - "8111:8111"
    volumes:
      - "~/docker/server/datadir:/data/teamcity_server/datadir"
      - "~/docker/server/logs:/opt/teamcity/logs"
    networks:
      - teamcity

  linux-agent-1:
    depends_on:
      - server
    environment:
      SERVER_URL: server:8111
      AGENT_NAME: docker-1
    image: "jetbrains/teamcity-agent:latest"
    networks:
      - teamcity

  linux-agent-2:
    depends_on:
      - server
    environment:
      SERVER_URL: server:8111
      AGENT_NAME: docker-2
    image: "jetbrains/teamcity-agent:latest"
    networks:
      - teamcity

  linux-agent-3:
    depends_on:
      - server
    environment:
      SERVER_URL: server:8111
      AGENT_NAME: docker-3
    image: "jetbrains/teamcity-agent:latest"
    networks:
      - teamcity

networks:
  teamcity:
